# Setup
title:               'Viet on Rails'
tagline:             'Ruby, Rails và nhiều thứ thú vị khác'
description:         'Cộng đồng những lập trình viên sử dụng Ruby, Rails và muốn trao đổi về nhiều thứ thú vị khác.'
url:                 http://vietonrails.com

# About/contact
author:
  name:              Luu Tuan Anh
  email:             rock.khuya@gmail.com

# Outputting
permalink: /:categories/:year/:month/:day/:title

# Markdown setting
kramdown:
  input: GFM
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# jekyll-tagging
tag_page_layout:     tag_page
tag_page_dir:        tag

gems:                [jekyll-paginate, jekyll-watch]

# jekyll-paginate
paginate:            5
paginate_path:       '/page:num'
